version: '3.3'
services:
  php-web:
    image: php-app
    container_name: php-web
    ports:
      - 8008:80
    depends_on:
      - php-postgres
    env_file:
      - .env
    volumes:
      - ./src:/var/www/html
  
  # Source: https://github.com/alexeagleson/docker-node-postgres-template/blob/master/docker-compose.yml
  php-postgres:
    image: postgres:16-alpine
    container_name: ${MONOLITHIC_POSTGRES_HOST}
    environment:
      POSTGRES_USER: ${MONOLITHIC_POSTGRES_USER}
      POSTGRES_PASSWORD: ${MONOLITHIC_POSTGRES_PASSWORD}
      POSTGRES_DB: ${MONOLITHIC_POSTGRES_DB}
    ports:
      # Standard port for PostgreSQL databases
      - "5432:${MONOLITHIC_POSTGRES_PORT}"
    volumes:
      # When the PostgresSQL container is started it will run any scripts
      # provided in the `docker-entrypoint-initdb.d` directory, this connects
      # our seed file to that directory so that it gets run
      - ./migration/database-seed.sql:/docker-entrypoint-initdb.d/database-seed.sql