version: '3.8'
services:
  rest-service:
    image: rest-service
    container_name: rest-service
    depends_on:
      - rest-db
    ports:
      - "3030:${REST_PORT}"
    env_file:
      - .env
    volumes:
      - ./index.ts:/app/index.ts
      - ./src:/app/src
      - ./prisma:/app/prisma
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json

  rest-db:
    image: postgres:16-alpine
    container_name: ${REST_POSTGRES_HOST}
    environment:
      POSTGRES_USER: ${REST_POSTGRES_USER}
      POSTGRES_PASSWORD: ${REST_POSTGRES_PASSWORD}
      POSTGRES_DB: ${REST_POSTGRES_DB}
    ports:
      - "5433:${REST_POSTGRES_PORT}"
    env_file:
      - .env
    # volumes:
    #   - ./database/database-seed:/docker-entrypoint-initdb.d/database-seed.sql